### ISSUE TITLE
synthesis unittests folder is missing __init__.py

### ISSUE THREAD

**Issue by dbogdanov** [jjaner/essentia-musicbricks#3]
Tests in synthesis folder are not recognized on Linux due to missing `__init__.py` file.

**Comment by jjaner** [comment]
Ok. I could not test it yet on Linux.  Have you added it already?

**Comment by dbogdanov** [comment]
Nope, I've just created a ticket for that. Simply copy a similar file from another folder.

**Comment by jjaner** [comment]
I added it.
