### ISSUE TITLE
SineModel streaming unit test fails

### ISSUE THREAD

**Issue by dbogdanov** [jjaner/essentia-musicbricks#4]
```
FAIL: testRegression (synthesis.test_sinemodel_streaming.TestSineModel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dbogdanov/essentia-jjaner/essentia-musicbricks/test/src/unittest/synthesis/test_sinemodel_streaming.py", line 226, in testRegression
    self.assertAlmostEqual(diffference/ref_diff, 1, 1e-6)
  File "/home/dbogdanov/essentia-jjaner/essentia-musicbricks/test/src/unittest/essentia_test.py", line 97, in assertAlmostEqual
    self.assert_(diff <= precision, 'Difference is %e while allowed precision is %e' % (diff, precision))
AssertionError: Difference is 4.544045e-06 while allowed precision is 1.000000e-06
```

**Comment by jjaner** [comment]
This is a general issue that needs further discussion for testing synthesis algorithms. 
This type of assert functions (e.g. AssertAlmostEqual) are computing a difference value as a relative value (diff = abs(_y - *x)/abs(_y)). This makes sense for general descriptors values, where it ensures a relative difference, but in case of comparing audio signals it does not make much sense. Low values ~0, have lower importance that higher values ~1, and the difference computation should take that into account. 

In these unit tests I considered as test signal x(t) = (0.5_sine(440_t)), and the precision was stablished as an empirical value on OSX. It is normal that it needs to be revised on other architectures. 

One option would be to implement a new AssertAlmostEqualAudio() function.

**Comment by dbogdanov** [comment]
We can implement new `AssertAlmostEqualAudio()` [here](https://github.com/jjaner/essentia-musicbricks/blob/master/test/src/unittest/essentia_test.py#L90). The function can check the difference in dBs, with a threshold set.

**Comment by dbogdanov** [comment]
I am still getting a FAIL in testRegression:

```
FAIL: testRegression (synthesis.test_sinemodel_streaming.TestSineModel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dbogdanov/essentia-jjaner/essentia-musicbricks/test/src/unittest/synthesis/test_sinemodel_streaming.py", line 226, in testRegression
    self.assertAlmostEqual(diffference/ref_diff, 1, 1e-6)
  File "/home/dbogdanov/essentia-jjaner/essentia-musicbricks/test/src/unittest/essentia_test.py", line 97, in assertAlmostEqual
    self.assert_(diff <= precision, 'Difference is %e while allowed precision is %e' % (diff, precision))
AssertionError: Difference is 4.544045e-06 while allowed precision is 1.000000e-06
```

**Comment by jjaner** [comment]
I changed the assert function for the testRegression, to have the fixed precision comparison, as in the STFT tests.  It still fails even when the difference is within the margin of 2 digits (40dB):
AssertionError: -0.4236263 != -0.42867586 within 2 places

Any idea?

**Comment by dbogdanov** [comment]
@jjaner 
-0.42 != -0.43

The assertAlmostEqualFixedPrecision is actually the [assertAlmostEqual](https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertAlmostEqual) from python's unittest library. 

It is written there that it tests _that first and second are approximately (or not approximately) equal by computing the difference, rounding to the given number of decimal places, and comparing to zero._

**Comment by jjaner** [comment]
Ok. I see. I modified the precision values accordingly so that it passes the tests with the set dB values. 
(commit 3d408d5e78dd67caa0e2cf92e2896f63c501c360 )

**Comment by dbogdanov** [comment]
Works now!
