### ISSUE TITLE
More algorithms are missing tests 

### ISSUE THREAD

**Issue by dbogdanov** [jjaner/essentia-musicbricks#6]
Unit tests are missing for the algorithms: 
- HarmonicMask
- SineSubtraction
- SpsModel*
- StochasticModel*

**Comment by jjaner** [comment]
Sure, I am on my way preparing the unit tests for all implemented synthesis algorithms (harmonic, spr, sps, hpr, hps models).
I did not manage to set a constant value as input of one algorithm (HarmonicModelAnal) when implementing the unit test. (see line 137 in the file  test_harmonicmodel_streaming  77a7dda4c7416c47b4dd4d0c21):
python all_tests.py harmonicmodel_streaming

What is the proper way to set an input to a constant value in streaming?

**Comment by jjaner** [comment]
I finished  implementing all unit tests for the synthesis algorithms, and merged into the master branch of this repository. commit a59944e8cad1364deb59043cf57e1e4c22760dc1

Let me know if you can run them and pass the tests.

**Comment by dbogdanov** [comment]
```
ERROR: testRegression (synthesis.test_hprmodel_streaming.TestHprModel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dbogdanov/essentia-jjaner/essentia-musicbricks/test/src/unittest/synthesis/test_hprmodel_streaming.py", line 243, in testRegression
    outsignal,pool = analsynthHprModelStreaming(self.params, signal)
  File "/home/dbogdanov/essentia-jjaner/essentia-musicbricks/test/src/unittest/synthesis/test_hprmodel_streaming.py", line 172, in analsynthHprModelStreaming
    print freqsClean
NameError: global name 'freqsClean' is not defined
```

**Comment by dbogdanov** [comment]
The rest works ok!
Missing a test for OverlapAdd

**Comment by jjaner** [comment]
I fixed the error on the hpr and added the unit test for the overlapadd:
commit 3583c861f5f09ecc5f6c77e5859d195944d489b9

Let me know if it passes all tests now.

**Comment by dbogdanov** [comment]
Works OK now.
